#!/bin/bash

echo "XSS Target Finder - Example Usage"
echo "=================================="
echo ""
echo "For Kali Linux / externally-managed Python environments:"
echo "  python3 -m venv venv"
echo "  source venv/bin/activate"
echo "  pip install -r requirements.txt"
echo ""
echo "Make sure to set your API keys first:"
echo "  HackerOne format: identifier:token"
echo "  export HACKERONE_API_KEY='abc123:1a2b3c4d5e6f'"
echo "  export BUGCROWD_API_KEY='your_bugcrowd_token'"
echo ""
echo "Example commands:"
echo ""
echo "1. Find reflected/stored XSS targets on both platforms:"
echo "   python xss_target_finder.py --reflected-stored"
echo ""
echo "2. Find DOM-based XSS targets with subdomain enumeration:"
echo "   python xss_target_finder.py --dom-based --subdomains"
echo ""
echo "3. Use only HackerOne for DOM-based XSS:"
echo "   python xss_target_finder.py --hackerone --dom-based"
echo "   python xss_target_finder.py -H --dom-based"
echo ""
echo "4. Use only BugCrowd for reflected/stored XSS:"
echo "   python xss_target_finder.py --bugcrowd --reflected-stored"
echo "   python xss_target_finder.py -B --reflected-stored"
echo ""
echo "5. Enable verbose mode to see detailed analysis:"
echo "   python xss_target_finder.py --reflected-stored --verbose"
echo "   python xss_target_finder.py --dom-based -v"
echo ""
echo "Press Ctrl+C to stop the tool at any time."

